name: '每日安全新闻'

on:
  watch:
    types: [started]
  schedule:
    - cron: '0 6 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: npm install
      - run: npm install xml2js@0.6.2
      - run: node ./plugins/days_secure.js
        env:
          bot_api: ${{ secrets.bot_api }}
